interns/urls.py
from django.urls import path, include
from interns import views
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views 

app_name = 'interns'

urlpatterns = [

    path('dashboard/', views.dashboard, name='dashboard'),
    path('home/', views.home, name='home'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),

]

kiams/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interns.urls')),
]

interns/models.py
from django.db import models

# Create your models here.

interns/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.utils import timezone



def dashboard(request):

        template_name = 'dashboard.html'

        return render(request, 'dashboard.html')

def home(request):

        template_name = 'home.html'

        return render(request, 'home.html')

interns/templates/base.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<script src="https://use.fontawesome.com/release/v5.0.8/js/all.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<html>

<head>

  <title>

  {% block title %}

  {% endblock %}

</title>

</head>

<body>

{% block header %}

{% endblock %}

{% block over_view_contact %}

{% endblock %}

<div style="background-color: white ;" align = "center">

{% block content %}

{% endblock %}

</div>

{% block footer %}

{% endblock %}

</body>


</html>

interns/templates/dashboard.html
{% extends "base.html" %}


{% block title %}

 Welcome to our site

{% endblock %}

{% block header %}

{% include "header.html" %}

{% endblock %}

{% block content %}

<div class="w3-content w3-section" style="max-width:600px">
  <img class="mySlides" src="/static/images/banner.jpg" style="width:115%; height:65%">
  <img class="mySlides" src="/static/images/img1.jpg" style="width:115%; height:65%">
  <img class="mySlides" src="/static/images/img2.jpg" style="width:115%; height:65%">
  <img class="mySlides" src="/static/images/img3.jpg" style="width:115%; height:65%">
  <img class="mySlides" src="/static/images/img4.jpg" style="width:115%; height:65%">
</div>

<script>
var slideIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > x.length) {slideIndex = 1}
    x[slideIndex-1].style.display = "block";
    setTimeout(carousel, 3000); // Change image every 2 seconds
}
</script>

<div class="w3-container">
<p>Copyright © 2016 PDTP Secretariat- ICT Authority. All rights reserved.</p>
</div>

{% endblock %}

{% block footer %}

{% include "footer.html" %}

{% endblock %}

interns/templates/header.html
{% extends "base.html" %}
{% block header %}
<!DOCTYPE html>
<html lang="en">

<nav class="navbar navbar-expand-sm bg-success navbar-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="/static/images/ketraco_logo.jpg" width="40" height="40" class="d-inline-block align-top" alt="">
      <span class="menu-collapsed"></span>
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#NavbarResponsive">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="NavbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/dashboard/">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login/">Login</a>
      </li>
    </ul>
  </div>
  </div>
</nav>

</html>
{% endblock %}

interns/templates/home.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<script js>
// Hide submenus
$('#body-row .collapse').collapse('hide');

// Collapse/Expand icon
$('#collapse-icon').addClass('fa-angle-double-left');

// Collapse click
$('[data-toggle=sidebar-colapse]').click(function() {
    SidebarCollapse();
});

function SidebarCollapse () {
    $('.menu-collapsed').toggleClass('d-none');
    $('.sidebar-submenu').toggleClass('d-none');
    $('.submenu-icon').toggleClass('d-none');
    $('#sidebar-container').toggleClass('sidebar-expanded sidebar-collapsed');

    // Treating d-flex/d-none on separators with title
    var SeparatorTitle = $('.sidebar-separator-title');
    if ( SeparatorTitle.hasClass('d-flex') ) {
        SeparatorTitle.removeClass('d-flex');
    } else {
        SeparatorTitle.addClass('d-flex');
    }

    // Collapse/Expand icon
    $('#collapse-icon').toggleClass('fa-angle-double-left fa-angle-double-right');
}
</script>

<!-- Bootstrap NavBar -->
<nav class="navbar navbar-expand-sm bg-success navbar-dark">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <img src="/static/images/ketraco_logo.jpg" width="40" height="40" class="d-inline-block align-top" alt="">
    <span class="menu-collapsed"></span>
  </a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a style='color: #FA0319' href="{% url 'interns:logout' %}">SIGN OUT</a>
      </li>

      <!-- This menu is hidden in bigger devices with d-sm-none.
           The sidebar isn't proper for smaller screens imo, so this dropdown menu can keep all the useful sidebar itens exclusively for smaller screens  -->
      <li class="nav-item dropdown d-sm-block d-md-none">
        <a class="nav-link dropdown-toggle" href="#" id="smallerscreenmenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="smallerscreenmenu">
            <a class="dropdown-item" href="#">Electrical</a>
            <a class="dropdown-item" href="#">Electrical</a>
            <a class="dropdown-item" href="#">Civil</a>
            <a class="dropdown-item" href="#">Reports</a>
        </div>
      </li><!-- Smaller devices menu END -->

    </ul>
  </div>
</nav><!-- NavBar END -->


<!-- Bootstrap row -->
<div class="row" id="body-row">
    <!-- Sidebar -->
    <div id="sidebar-container" class="sidebar-expanded d-none d-md-block"><!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
        <!-- Bootstrap List Group -->
        <ul class="list-group">
            <!-- Separator with title -->
            <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                <small>TRAINING MATERIALS</small>
            </li>
            <!-- /END Separator -->
            <!-- Menu with submenu -->
            <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="menu-collapsed">ELETRICAL</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu1' class="collapse sidebar-submenu">
                <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Transmitions</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Substations</span>
                </a>
            </div>
            <a href="#submenu2" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">ELECTROMECHANICAL</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu2' class="collapse sidebar-submenu">
                <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Electromechanical</span>
                </a>

            </div>

            <a href="#submenu3" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">CIVIL</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu3' class="collapse sidebar-submenu">
                <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Civil</span>
                </a>

            </div>

            <!-- Separator with title -->
            <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                <small>OTHER OPTIONS</small>
            </li>
            <!-- /END Separator -->
            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">Reports <span class="badge badge-pill badge-primary ml-2"></span></span>
                </div>
            </a>

            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">Safety</span>
                </div>
            </a>
            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">Evaluation <span class="badge badge-pill badge-primary ml-2"></span></span>
                </div>
            </a>

            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">Deplyoment and Location<span class="badge badge-pill badge-primary ml-2"></span></span>
                </div>
            </a>

            <!-- Separator without title -->
            <li class="list-group-item sidebar-separator menu-collapsed"></li>
            <!-- /END Separator -->
            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">

                    <span class="menu-collapsed">Raise an Issue</span>
                </div>
            </a>


        </ul><!-- List Group END-->
    </div><!-- sidebar-container END -->

    <!-- MAIN -->
    <div class="col">

        <h1>
            KIAMS PORTAL
            <small class="text-muted"></small>
        </h1>


        <div class="card">
            <h4 class="card-header">News Feed</h4>
            <div class="card-body">
                <ul>
                    <li>*Current Ketraco Projects</li>
                    <li>*Recent Accomplishment</li>
                    <li>*Updates</li>
                </ul>
            </div>
        </div>



    </div><!-- Main Col END -->

</div><!-- body-row END -->

<div class="w3-container">
<p>Copyright © 2016 PDTP Secretariat- ICT Authority. All rights reserved.</p>
</div>

</div>


{% else %}

  <p>You are not logged in</p>

  <a href="{% url 'login' %}">login</a>

{% endif %}

{% endblock %}

{% block footer %}

{% include "footer.html" %}

{% endblock %}